# =============================================================================
# Service リソース
# =============================================================================
# Service が必要な場合は、kustomization.yaml の resources から service.yaml を追加してください。
#
# containerPort を変更する場合は deployment-patch.yaml も合わせて変更してください。
# =============================================================================

apiVersion: v1
kind: Service
metadata:
  name: script-runner
  labels:
    app.kubernetes.io/name: script-runner
    app.kubernetes.io/component: deployment
    # テナント名
    edge.kudpc.kyoto-u.ac.jp/egress-policy: "your-tenant-name"
  annotations:
    # 割当IPアドレス
    io.cilium/lb-ipam-ips: "192.0.2.1"
    # namespace名
    io.cilium/lb-ipam-sharing-key: "your-namespace-name"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: script-runner
    app.kubernetes.io/component: deployment
  loadBalancerSourceRanges:
    - 0.0.0.0/0