apiVersion: v1
kind: Service
metadata:
  name: script-runner
  labels:
    app.kubernetes.io/name: script-runner
    app.kubernetes.io/component: deployment
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    serviceSelectorLabel: my-label
